tasks:
  - name: Setup environment and PHP/Composer dependencies
    openMode: split-left
    init: |
      cp .env.example .env
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env
      gp sync-done vite-url
      composer install
      php artisan key:generate
      php artisan storage:link
      touch database/database.sqlite
      php artisan migrate:fresh --seed
      php artisan serve

  - name: Install Node dependencies and run Vite
    openMode: split-right
    command: |
      gp sync-await vite-url
      npm install
      npm run dev

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Node Server for Vite

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
